config/routes.rb
Rails.application.routes.draw do
  apipie
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  namespace :api do
    namespace :v1 do
      resources :countries
    end
  end
  resources :countries
  # Defines the root path route ("/")
  root "home#index"
  get 'admin/index'
  post 'restore_record/create'
  post 'soft_delete_record/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, :alpha_2_code, :alpha_3_code, :currency, presence: true

  def soft_delete
    self.soft_deleted_at = Time.now
    self.save!
  end

  alias :destroy :soft_delete
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def index
        @all_records = if params[:state] == 'all records'
            true
        else
            false
        end

        if @all_records

            @countries = Country.all
        else
        @countries = Country.where(soft_deleted_at: nil)
        end
    end
end

app/controllers/api/v1/countries_controller.rb
module Api
  module V1
    class CountriesController < ApplicationController
      before_action :set_country, only: %i[ show destroy ]
      api :GET, "/v1/countries", "List Countries"
      api :GET, "/v1/countries?currency=value", "Filter Countries by their currency"
      param :currency, String, :desc => "Country currency ", :required => false
      error :code => 404, :desc => "Not Found", :meta => {:reason => "record not found"}

      def index
        @countries = Country.where(soft_deleted_at: nil)

        @countries = @countries.where('currency LIKE ?', "%#{params[:currency]}%") if params[:currency]

        if @countries
          render json: {status: "SUCCESS", message: "Fetched all the countries successfully", data: @countries}, status: :ok
        else
          render json: @countries.errors, status: :bad_request
        end
      end

      api :GET, "/v1/countries/alpha_code", "Fetch a single country by its alpha_2_code or alpha_3_code"
      error :code => 404, :desc => "Not Found"
      param :alpha_2_code, String, :desc => "Country alpha 2 code", :required => false
      param :alpha_3_code, String, :desc => "Country alpha 3 code", :required => false
      def show
        if @country.presence
          render json: @country
        else
          render json: {status: "Failure", code: 404,  message: "Record not found", data: @country}, status: :not_found
        end
      end

      def destroy
        @country.soft_delete
      end

      private

      def set_country
        @country = Country.where('alpha_2_code = ? or alpha_3_code = ? or id = ?', params[:id], params[:id], params[:id]).first
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/restore_record_controller.rb
class RestoreRecordController < ApplicationController
    def create
        @record = Country.find(params[:id])

        @record.soft_deleted_at = nil
      if @record.save
       flash[:notice] = 'Country was successfully restored.'
       redirect_to admin_index_url
    else
        flash[:notice] = 'Could not restored the record.'
        redirect_to admin_index_url
    end
end


end

app/controllers/soft_delete_record_controller.rb
class SoftDeleteRecordController < ApplicationController
  def create

    @record = Country.find(params[:id])
    @record.soft_deleted_at = Time.now
    if @record.save
      flash[:notice] = 'Record was successfully deleted .'
      redirect_to admin_index_url
    else
      flash[:notice] = 'Could not delete the record.'
      redirect_to admin_index_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Country</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Alpha 2 Code</th>
      <th scope="col">Alpha 3 Code</th>
      <th scope="col">Currency</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></th>
        <td><%= country.alpha_2_code %></td>
        <td> <%= country.alpha_3_code %></td>
        <td>  <%= country.currency %></td>
        <td>
          <% if country.soft_deleted_at.nil? %>
            <%= button_to "Soft Delete Record", soft_delete_record_create_path(id: country.id) %>
          <% else %>
            <%= button_to "Restore Record", restore_record_create_path(id: country.id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @all_records %>
  <%= link_to "View only Undiscarded Records", admin_index_path%>
<% else %>
  <%= link_to "View all including Discarded Records", admin_index_path(state: "all records")%>
<% end %>

app/views/home/index.html.erb
<div>
<h1> Country Information Service</h1>
<ul>
<%=link_to "Api Documentation", apipie_apipie_path %>
<%=link_to "Admin Interface", admin_index_path %>

</ul>
<div>

app/views/layouts/apipie/apipie.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('apipie.api_documentation', :default => 'Api Documentation') %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= Apipie.include_stylesheets %>
  <link type='text/css' rel='stylesheet' href='<%= Apipie.full_url("stylesheets/application.css")%>'/>
  <!-- IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div class="container-fluid">
    <div class="row-fluid">
      <div id='container'>
        <%= yield %>
        <%= render 'disqus' if Apipie.configuration.use_disqus? %>
      </div>
    </div>
    <hr>
    <footer><%= yield :apipie_footer %></footer>
  </div>
  <%= Apipie.include_javascripts %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CountryInformationService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>